apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw-ingress
  namespace: homework
  annotations:
    nginx.ingress.kubernetes.io/app-root: /homepage
    nginx.ingress.kubernetes.io/rewrite-target: /index.html
spec:
  ingressClassName: nginx
  rules:
  - host: kubernetes.networks
    http:
      paths:
      - path: /homepage
        pathType: Exact
        backend:
          service:
            name: hw-service
            port:
              number: 80
