apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw-app
  template:
    metadata:
      labels:
        app: hw-app
    spec:
      containers:
      - name: hw-app-container
        image: kali7va/ngx-metrics:0.4
        readinessProbe:
          httpGet:
            path: /health
            port: 80
      - name: hw-app-metrics-exporter
        image: nginx/nginx-prometheus-exporter:1.5.1
        env:
        - name: SCRAPE_URI
          value: http://localhost:80/metrics
        ports:
          - containerPort: 9113
