apiVersion: v1
kind: Service
metadata:
  name: hw-service
  namespace: homework
spec:
  type: NodePort
  selector:
    app: hw-app
  ports:
  - name: app-port
    port: 80
    targetPort: 80
  - name: metrics-exporter-port
    port: 9113
    targetPort: 9113
